apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.fullname }}
spec:
  selector:
    app: {{ .Values.fullname }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
