replicaCount: 1

fullname: cours

image:
  repository: wikimax/cours
  tag: latest
  pullPolicy: Always

service:
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: cours.toastcie.dev
